name: A4060
description: A trading strategy simulator with 40/60 capital protection rule.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  provider: ^6.1.3 # Updated to the latest version
  intl: ^0.18.0 # Updated to a more recent version
  fl_chart: ^0.36.0 # Updated to the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Downgrade to version 4.0.0


flutter:
  uses-material-design: true
